[package]
name = "typit"
version = "0.1.0"
edition = "2021"
authors = ["Abi"]

[dependencies]
colored = "2.0"
inquire = "0.7.5"
rand = "0.8.5"
clipboard = "0.5"
meval = "0.2.0"
sha256 = "1.0"
mac_address = "1.1.7"